# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir G:/FPU/r64_SRT_fcbrt/vivadopro/fcbrt64/fcbrt64.cache/wt [current_project]
set_property parent.project_path G:/FPU/r64_SRT_fcbrt/vivadopro/fcbrt64/fcbrt64.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo g:/FPU/r64_SRT_fcbrt/vivadopro/fcbrt64/fcbrt64.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog G:/FPU/r64_SRT_fcbrt/src/common_cells/assertions.svh
set_property file_type "Verilog Header" [get_files G:/FPU/r64_SRT_fcbrt/src/common_cells/assertions.svh]
read_verilog -library xil_defaultlib -sv {
  G:/FPU/r64_SRT_fcbrt/src/common_cells/CLA_15bit.sv
  G:/FPU/r64_SRT_fcbrt/src/common_cells/CSA4_2.sv
  G:/FPU/r64_SRT_fcbrt/src/common_cells/cf_math_pkg.sv
  G:/FPU/r64_SRT_fcbrt/src/fcbrt_ML_PLAC.sv
  G:/FPU/r64_SRT_fcbrt/src/fcbrt_Residual_r4.sv
  G:/FPU/r64_SRT_fcbrt/src/fcbrt_S_SM_r4.sv
  G:/FPU/r64_SRT_fcbrt/src/fcbrt_Ssel.sv
  G:/FPU/r64_SRT_fcbrt/src/fcbrt_Ssquare_r4.sv
  G:/FPU/r64_SRT_fcbrt/src/fcbrt_defs.sv
  G:/FPU/r64_SRT_fcbrt/src/fcbrt_core.sv
  G:/FPU/r64_SRT_fcbrt/src/fcbrt_postprocess.sv
  G:/FPU/r64_SRT_fcbrt/src/fcbrt_preprocess.sv
  G:/FPU/r64_SRT_fcbrt/src/common_cells/fcbrt_udiv3.sv
  G:/FPU/r64_SRT_fcbrt/src/common_cells/lzc.sv
  G:/FPU/r64_SRT_fcbrt/src/fcbrt_top.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc G:/FPU/r64_SRT_fcbrt/vivadopro/fcbrt64/fcbrt64.srcs/constrs_1/new/ff.xdc
set_property used_in_implementation false [get_files G:/FPU/r64_SRT_fcbrt/vivadopro/fcbrt64/fcbrt64.srcs/constrs_1/new/ff.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top fcbrt_top -part xc7a100tcsg324-3


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fcbrt_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file fcbrt_top_utilization_synth.rpt -pb fcbrt_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
